/* file: deca_double.h */

/* This file contains the header files for a standalone,
   self-contained collection of routines for deca double arithmetic,
   based on the CAMPARY and the QD software libraries.

All functions in this library have the prefix da_
to avoid potential name clashes with other multiple doubles. */

#ifndef __deca_double_h__
#define __deca_double_h__

/************************* normalizations ************************/

void da_renorm10
 ( double f0, double f1, double f2, double f3, double f4, double f5,
   double f6, double f7, double f8, double f9, double f10, double *pr,
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9 );
/*
 * DESCRIPTION :
 *   Definitions common to fast_renorm2L<11,10> and renorm2L_4Add1<10,10>
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   f0       most significant word;
 *   f1       second most significant word;
 *   f2       third most significant word;
 *   f3       fourth most significant word;
 *   f4       fifth most significant word;
 *   f5       sixth most significant word;
 *   f6       seventh most significant word;
 *   f7       eighth most significant word;
 *   f8       nineth most significant word;
 *   f9       tenth most significant word;
 *   f10      least significant word;
 *   pr       computed by the start of the renormalization.
 *
 * ON RETURN :
 *   pr       updated value by renormalization;
 *   r0       highest part of a deca double number;
 *   r1       second highest part of a deca double number;
 *   r2       third highest part of a deca double number.
 *   r3       fourth highest part of a deca double number;
 *   r4       fifth highest part of a deca double number;
 *   r5       fifth lowest part of a deca double number;
 *   r6       fourth lowest part of a deca double number;
 *   r7       third lowest part of a deca double number;
 *   r8       second lowest part of a deca double number;
 *   r9       lowest part of a deca double number. */

void da_fast_renorm
 ( double x0, double x1, double x2, double x3, double x4, double x5,
   double x6, double x7, double x8, double x9, double x10,
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9 );
/*
 * DESCRIPTION :
 *   The definition is based on the fast_renorm2L<11,10>,
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   x0       most significant word;
 *   x1       second most significant word;
 *   x2       third most significant word;
 *   x3       fourth most significant word;
 *   x4       fifth most significant word;
 *   x5       sixth most significant word;
 *   x6       seventh most significant word;
 *   x7       eighth most significant word;
 *   x8       nineth most significant word;
 *   x9       tenth most significant word;
 *   x10      least significant word.
 *
 * ON RETURN :
 *   r0       highest part of an deca double number;
 *   r1       second highest part of an deca double number;
 *   r2       third highest part of an deca double number.
 *   r3       fourth highest part of an deca double number;
 *   r4       fifth highest part of an deca double number;
 *   r5       fifth lowest part of an deca double number;
 *   r6       fourth lowest part of an deca double number;
 *   r7       third lowest part of an deca double number;
 *   r8       second lowest part of an deca double number;
 *   r9       lowest part of an deca double number. */

void da_renorm_add1
 ( double x0, double x1, double x2, double x3, double x4, double x5,
   double x6, double x7, double x8, double x9, double y,
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9 );
/*
 * DESCRIPTION :
 *   The definition is based on the renorm2L_4Add1<10,10>,
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   x0       most significant word of an deca double x;
 *   x1       second most significant word of an deca double x;
 *   x2       third most significant word of an deca double x;
 *   x3       fourth most significant word of an deca double x;
 *   x4       fifth most significant word of an deca double x;
 *   x5       fifth lowest part of an deca double number x;
 *   x6       fourth lowest part of an deca double number x;
 *   x7       third lowest part of an deca double number x;
 *   x8       second lowest part of an deca double number x;
 *   x9       least significant word of an deca double x;
 *   y        double to be added to x.
 *
 * ON RETURN :
 *   r0       highest part of x + y;
 *   r1       second highest part of x + y;
 *   r2       third highest part of x + y;
 *   r3       fourth highest part of x + y;
 *   r4       fifth highest part of x + y;
 *   r5       fifth lowest part of x + y;
 *   r6       fourth lowest part of x + y;
 *   r7       third lowest part of x + y;
 *   r8       second lowest part of x + y;
 *   r9       lowest part of x + y. */

/****************************** copy *****************************/

void da_copy ( const double *a, double *b );
/*
 * DESCRIPTION :
 *   Copies the content of the deca double a to the deca double b. */

/******************* addition and subtraction *********************/

/* deca double = deca double + deca double */
void da_add ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a + b, or in words:
 *   Adds two deca doubles in a and b to make the deca double c. */

/* deca double = deca double + double */
void da_add_da_d ( const double *a, double b, double *c );
/*
 * DESCRIPTION : c = a + b, or in words:
 *   Adds the deca double in a and the double b
 *   to make the deca double c. */

/* deca double = - deca double */
void da_minus ( double *a );
/*
 * DESCRIPTION :
 *   Flips the sign of a. */

/* deca double = deca double + deca double */
void da_sub ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a - b, or in words:
 *   Subtracts from the deca double in a
 *   the deca double in b to make the deca double c. */

/**************  multiplications and division ***********************/

/* deca double = deca double * deca double */
void da_mul ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a * b, or in words:
 *   Multiples the deca doubles a and b to make the deca double c. */

/* deca double = deca double * double */
void da_mul_da_d ( const double *a, double b, double *c );
/*
 * DESCRIPTION : c = a * b, or in words:
 *   Multiples the deca double a with the double b
 *   to make the deca double c. */

/* deca double = deca double / deca double */
void da_div ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a / b, or in words:
 *   Divides the deca double a by the deca double b
 *   to make the deca double c. */

/******************* random number generator ***************************/

void da_random ( double *x );
/*
 * DESCRIPTION :
 *   Returns in x a random deca double number in [0,1]. */

/************************ basic output *********************************/

void da_write_doubles ( const double *x );
/*
 * DESCRIPTION :
 *   Writes the doubles in the deca double number x. */

#endif /* __deca_double_h__ */
