/* file: hexa_double.h */

/* This file contains the header files for a standalone,
   self-contained collection of routines for hexa double arithmetic,
   based on the CAMPARY and the QD software libraries.

All functions in this library have the prefix hd_
to avoid potential name clashes with other multiple doubles. */

#ifndef __hexa_double_h__
#define __hexa_double_h__

/************************* normalizations ************************/

void hd_renorm16
 ( double f0, double f1, double f2, double f3, double f4, double f5,
   double f6, double f7, double f8, double f9, double f10, double f11,
   double f12, double f13, double f14, double f15, double f16, double *pr, 
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9, double *r10, double *r11,
   double *r12, double *r13, double *r14, double *r15 );
/*
 * DESCRIPTION :
 *   Definitions common to fast_renorm2L<17,16> and renorm2L_4Add1<16,16>
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   f0       most significant word;
 *   f1       second most significant word;
 *   f2       third most significant word;
 *   f3       fourth most significant word;
 *   f4       fifth most significant word;
 *   f5       sixth most significant word;
 *   f6       seventh most significant word;
 *   f7       eighth most significant word;
 *   f8       nineth most significant word;
 *   f9       tenth most significant word;
 *   f10      eleventh most significant word;
 *   f11      twelveth most significant word;
 *   f12      thirteenth most significant word;
 *   f13      forteenth most significant word;
 *   f14      fifteenth most significant word;
 *   f15      sixteenth most significant word;
 *   f16      least significant word.
 *   pr       computed by the start of the renormalization.
 *
 * ON RETURN :
 *   pr       updated value by renormalization;
 *   r0       highest part of a hexa double number;
 *   r1       second highest part of an hexa double number;
 *   r2       third highest part of an hexa double number.
 *   r3       fourth highest part of an hexa double number;
 *   r4       fifth highest part of an hexa double number;
 *   r5       sixth highest part of an hexa double number;
 *   r6       seventh highest part of an hexa double number;
 *   r7       eighth highest part of an hexa double number;
 *   r8       eighth lowest part of an hexa double number;
 *   r9       seventh lowest part of an hexa double number;
 *   r10      sixth lowest part of an hexa double number;
 *   r11      fifth lowest part of an hexa double number;
 *   r12      fourth lowest part of an hexa double number;
 *   r13      third lowest part of an hexa double number;
 *   r14      second lowest part of an hexa double number;
 *   r15      lowest part of an hexa double number. */

void hd_fast_renorm
 ( double x0, double x1, double x2, double x3, double x4, double x5,
   double x6, double x7, double x8, double x9, double x10, double x11,
   double x12, double x13, double x14, double x15, double x16,
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9, double *r10, double *r11,
   double *r12, double *r13, double *r14, double *r15 );
/*
 * DESCRIPTION :
 *   The definition is based on the fast_renorm2L<17,16>,
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   x0       most significant word;
 *   x1       second most significant word;
 *   x2       third most significant word;
 *   x3       fourth most significant word;
 *   x4       fifth most significant word;
 *   x5       sixth most significant word;
 *   x6       seventh most significant word;
 *   x7       eighth most significant word;
 *   x8       nineth most significant word;
 *   x9       tenth most significant word;
 *   x10      eleventh most significant word;
 *   x11      twelveth most significant word;
 *   x12      thirteenth most significant word;
 *   x13      forteenth most significant word;
 *   x14      fifteenth most significant word;
 *   x15      sixteenth most significant word;
 *   x16      least significant word.
 *
 * ON RETURN :
 *   r0       highest part of a hexa double number;
 *   r1       second highest part of an hexa double number;
 *   r2       third highest part of an hexa double number.
 *   r3       fourth highest part of an hexa double number;
 *   r4       fifth highest part of an hexa double number;
 *   r5       sixth highest part of an hexa double number;
 *   r6       seventh highest part of an hexa double number;
 *   r7       eighth highest part of an hexa double number;
 *   r8       eighth lowest part of an hexa double number;
 *   r9       seventh lowest part of an hexa double number;
 *   r10      sixth lowest part of an hexa double number;
 *   r11      fifth lowest part of an hexa double number;
 *   r12      fourth lowest part of an hexa double number;
 *   r13      third lowest part of an hexa double number;
 *   r14      second lowest part of an hexa double number;
 *   r15      lowest part of an hexa double number. */

void hd_renorm_add1
 ( double x0, double x1, double x2, double x3, double x4, double x5,
   double x6, double x7, double x8, double x9, double x10, double x11,
   double x12, double x13, double x14, double x15, double y,
   double *r0, double *r1, double *r2, double *r3, double *r4, double *r5,
   double *r6, double *r7, double *r8, double *r9, double *r10, double *r11,
   double *r12, double *r13, double *r14, double *r15 );
/*
 * DESCRIPTION :
 *   The definition is based on the renorm2L_4Add1<16,16>,
 *   from code of the specRenorm.h, generated by the CAMPARY library,
 *   in an unrolled form (Valentina Popescu, Mioara Joldes), with
 *   double double basics of QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey).
 *
 * ON ENTRY :
 *   x0       most significant word of an hexa double x;
 *   x1       second most significant word of an hexa double x;
 *   x2       third most significant word of an hexa double x;
 *   x3       fourth most significant word of an hexa double x;
 *   x4       fifth most significant word of an hexa double x;
 *   x5       sixth most significant word of an hexa double x;
 *   x6       seventh most significant word of an hexa double x;
 *   x7       eighth most significant word of an hexa double x;
 *   x8       eighth least significant word of an hexa double number x;
 *   x9       seventh least significant word of an hexa double number x;
 *   x10      sixth least significant word of an hexa double number x;
 *   x11      fifth least significant word of an hexa double number x;
 *   x12      fourth least significant word of an hexa double number x;
 *   x13      third least significant word of an hexa double number x;
 *   x14      second least significant word of an hexa double number x;
 *   x15      least significant word of an hexa double x;
 *   y        double to be added to x.
 *
 * ON RETURN :
 *   r0       highest part of x + y;
 *   r1       second highest part of x + y;
 *   r2       third highest part of x + y;
 *   r3       fourth highest part of x + y;
 *   r4       fifth highest part of x + y;
 *   r5       sixth highest part of x + y;
 *   r6       seventh highest part of x + y;
 *   r7       eighth highest part of x + y;
 *   r8       eighth lowest part of x + y;
 *   r9       seventh lowest part of x + y;
 *   r10      sixth lowest part of x + y;
 *   r11      fifth lowest part of x + y;
 *   r12      fourth lowest part of x + y;
 *   r13      third lowest part of x + y;
 *   r14      second lowest part of x + y;
 *   r15      lowest part of x + y. */

/****************************** copy *****************************/

void hd_copy ( const double *a, double *b );
/*
 * DESCRIPTION :
 *   Copies the content of the hexa double a to the hexa double b. */

/******************* addition and subtraction *********************/

/* hexa double = hexa double + hexa double */
void hd_add ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a + b, or in words:
 *   Adds two hexa doubles in a and b to make the hexa double c. */

/* hexa double = hexa double + double */
void hd_add_hd_d ( const double *a, double b, double *c );
/*
 * DESCRIPTION : c = a + b, or in words:
 *   Adds the hexa double in a and the double b
 *   to make the hexa double c. */

/* hexa double = - hexa double */
void hd_minus ( double *a );
/*
 * DESCRIPTION :
 *   Flips the sign of a. */

/* hexa double = hexa double + hexa double */
void hd_sub ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a - b, or in words:
 *   Subtracts from the hexa double in a
 *   the hexa double in b to make the hexa double c. */

/**************  multiplications and division ***********************/

/* hexa double = hexa double * hexa double */
void hd_mul ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a * b, or in words:
 *   Multiplies the hexa doubles a and b to make the hexa double c. */

/* hexa double = hexa double * double */
void hd_mul_hd_d ( const double *a, double b, double *c );
/*
 * DESCRIPTION : c = a * b, or in words:
 *   Multiplies the hexa double a with the double b
 *   to make the hexa double c. */

/* hexa double = hexa double / hexa double */
void hd_div ( const double *a, const double *b, double *c );
/*
 * DESCRIPTION : c = a / b, or in words:
 *   Divides the hexa double a by the hexa double b
 *   to make the hexa double c. */

/******************* random number generator ***************************/

void hd_random ( double *x );
/*
 * DESCRIPTION :
 *   Returns in x a random hexa double number in [0,1]. */

/************************ basic output *********************************/

void hd_write_doubles ( const double *x );
/*
 * DESCRIPTION :
 *   Writes the doubles in the hexa double number x. */

#endif /* __hexa_double_h__ */
