/* file: penta_double.c */

/* This file contains the corresponding C code for the functions
   with prototypes declared in the penta_double.h file. */

#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include "double_double.h"
#include "penta_double.h"

/************************* normalizations ************************/

void pd_renorm5
 ( double f0, double f1, double f2, double f3, double f4, double f5,
   double *pr, double *r0, double *r1, double *r2, double *r3, double *r4 )
{
   int ptr;

   if(f1 == 0.0)
   {
      *pr = f0;
      ptr = 0;
      *r0 = dd_quick_two_sum(*pr,f2,pr);
   }
   else
   {
      *r0 = f0;
      *pr = f1;
      ptr = 1;
      *r1 = dd_quick_two_sum(*pr,f2,pr);
   }
   if(*pr == 0.0)
   {
      if(ptr == 0)
         *pr = *r0;
      else
         *pr = *r1;
   }
   else
   {
      ptr = ptr + 1;
   }
   if(ptr == 0)
   {
      *r0 = dd_quick_two_sum(*pr,f3,pr);
   }
   else if(ptr == 1)
   {
      *r1 = dd_quick_two_sum(*pr,f3,pr);
   }
   else if(ptr == 2)
   {
      *r2 = dd_quick_two_sum(*pr,f3,pr);
   }

   if(*pr == 0.0)
   {
      if(ptr == 0)
      {
         *pr = *r0;
      }
      else if(ptr == 1)
      {
         *pr = *r1;
      }
      else if(ptr == 2)
      {
         *pr = *r2;
      }
   }
   else
   {
      ptr = ptr + 1;
   }
   if(ptr == 0)
   {
      *r0 = dd_quick_two_sum(*pr,f4,pr);
   }
   else if(ptr == 1)
   {
      *r1 = dd_quick_two_sum(*pr,f4,pr);
   }
   else if(ptr == 2)
   {
      *r2 = dd_quick_two_sum(*pr,f4,pr);
   }
   else if(ptr == 3)
   {
      *r3 = dd_quick_two_sum(*pr,f4,pr);
   }

   if(*pr == 0.0)
   {
      if(ptr == 0)
      {
         *pr = *r0;
      }
      else if(ptr == 1)
      {
         *pr = *r1;
      }
      else if(ptr == 2)
      {
         *pr = *r2;
      }
      else if(ptr == 3)
      {
         *pr = *r3;
      }
   }
   else
   {
      ptr = ptr + 1;
   }
   if(ptr == 0)
   {
      *r0 = dd_quick_two_sum(*pr,f5,pr);
   }
   else if(ptr == 1)
   {
      *r1 = dd_quick_two_sum(*pr,f5,pr);
   }
   else if(ptr == 2)
   {
      *r2 = dd_quick_two_sum(*pr,f5,pr);
   }
   else if(ptr == 3)
   {
      *r3 = dd_quick_two_sum(*pr,f5,pr);
   }
   else if(ptr == 4)
   {
      *r4 = dd_quick_two_sum(*pr,f5,pr);
   }

   if(*pr == 0.0)
   {
      if(ptr == 0)
      {
         *pr = *r0;
      }
      else if(ptr == 1)
      {
         *pr = *r1;
      }
      else if(ptr == 2)
      {
         *pr = *r2;
      }
      else if(ptr == 3)
      {
         *pr = *r3;
      }
      else if(ptr == 4)
      {
         *pr = *r4;
      }
   }
   else
   {
      ptr = ptr + 1;
   }
   if((ptr < 5) && (*pr != 0.0))
   {
      if(ptr == 0)
      {
         *r0 = *pr;
      }
      else if(ptr == 1)
      {
         *r1 = *pr;
      }
      else if(ptr == 2)
      {
         *r2 = *pr;
      }
      else if(ptr == 3)
      {
         *r3 = *pr;
      }
      else if(ptr == 4)
      {
         *r4 = *pr;
      }
      ptr = ptr + 1;
   }
   if(ptr < 1)
   {
      *r4 = 0.0; *r3 = 0.0; *r2 = 0.0; *r1 = 0.0; *r0 = 0.0;
   }
   else if(ptr < 2)
   {
      *r4 = 0.0; *r3 = 0.0; *r2 = 0.0; *r1 = 0.0;
   }
   else if(ptr < 3)
   {
      *r4 = 0.0; *r3 = 0.0; *r2 = 0.0;
   }
   else if(ptr < 4)
   {
      *r4 = 0.0; *r3 = 0.0;
   }
   else if(ptr < 5)
   {
      *r4 = 0.0;
   }
}

void pd_fast_renorm
 ( double x0, double x1, double x2, double x3, double x4, double x5,
   double *r0, double *r1, double *r2, double *r3, double *r4 )
{
   double f0,f1,f2,f3,f4,f5,pr;

   pr = dd_quick_two_sum(x4,x5,&f5);
   pr = dd_quick_two_sum(x3,pr,&f4);
   pr = dd_quick_two_sum(x2,pr,&f3);
   pr = dd_quick_two_sum(x1,pr,&f2);
   f0 = dd_quick_two_sum(x0,pr,&f1);

   pd_renorm5(f0,f1,f2,f3,f4,f5,&pr,r0,r1,r2,r3,r4);
}

void pd_renorm_add1
 ( double x0, double x1, double x2, double x3, double x4, double y,
   double *r0, double *r1, double *r2, double *r3, double *r4 )
{
   double f0,f1,f2,f3,f4,f5,pr;

   pr = dd_two_sum(x4,y,&f5);
   pr = dd_two_sum(x3,pr,&f4);
   pr = dd_two_sum(x2,pr,&f3);
   pr = dd_two_sum(x1,pr,&f2);
   f0 = dd_two_sum(x0,pr,&f1);

   pd_renorm5(f0,f1,f2,f3,f4,f5,&pr,r0,r1,r2,r3,r4);
}

/****************************** copy *****************************/

void pd_copy ( const double *a, double *b )
{
   b[0] = a[0];
   b[1] = a[1];
   b[2] = a[2];
   b[3] = a[3];
   b[4] = a[4];
}

/******************* addition and subtraction *********************/

void pd_add ( const double *a, const double *b, double *c )
{
   // ALGORITHM : baileyAdd_fast<5,5,5> generated by CAMPARY.

   double f0,f1,f2,f3,f4,f5,e;

   f5 = 0.0;
   f4 = dd_two_sum(a[4],b[4],&e);
   f5 = f5 + e;
   f3 = dd_two_sum(a[3],b[3],&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f2 = dd_two_sum(a[2],b[2],&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f1 = dd_two_sum(a[1],b[1],&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f0 = dd_two_sum(a[0],b[0],&e);
   f1 = dd_two_sum(f1,e,&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;

   pd_fast_renorm(f0,f1,f2,f3,f4,f5,&c[0],&c[1],&c[2],&c[3],&c[4]);
}

void pd_add_pd_d ( const double *a, double b, double *c )
{
   pd_renorm_add1(a[0],a[1],a[2],a[3],a[4],b,&c[0],&c[1],&c[2],&c[3],&c[4]);
}

void pd_minus ( double *a )
{
   a[0] = -a[0];
   a[1] = -a[1];
   a[2] = -a[2];
   a[3] = -a[3];
   a[4] = -a[4];
}

void pd_sub ( const double *a, const double *b, double *c )
{
   double minb[5];

   pd_copy(b,minb);
   pd_minus(minb);
   pd_add(a,minb,c);
}

/**************  multiplication and division ***********************/

void pd_mul ( const double *a, const double *b, double *c )
{
   // ALGORITHM : baileyMul_fast<5,5,5> generated by CAMPARY.

   double f0,f1,f2,f3,f4,f5,p,e;

   f5 =      a[1]*b[4];
   f5 = f5 + a[2]*b[3];
   f5 = f5 + a[3]*b[2];
   f5 = f5 + a[4]*b[1];

   f4 = dd_two_prod(a[0],b[4],&e);
   f5 = f5 + e;
   p = dd_two_prod(a[1],b[3],&e);
   f5 = f5 + e;
   f4 = dd_two_sum(f4,p,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[2],b[2],&e);
   f5 = f5 + e;
   f4 = dd_two_sum(f4,p,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[3],b[1],&e);
   f5 = f5 + e;
   f4 = dd_two_sum(f4,p,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[4],b[0],&e);
   f5 = f5 + e;
   f4 = dd_two_sum(f4,p,&e);
   f5 = f5 + e;
   f3 = dd_two_prod(a[0],b[3],&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[1],b[2],&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f3 = dd_two_sum(f3,p,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[2],b[1],&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f3 = dd_two_sum(f3,p,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[3],b[0],&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f3 = dd_two_sum(f3,p,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f2 = dd_two_prod(a[0],b[2],&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[1],b[1],&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f2 = dd_two_sum(f2,p,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[2],b[0],&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f2 = dd_two_sum(f2,p,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f1 = dd_two_prod(a[0],b[1],&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   p = dd_two_prod(a[1],b[0],&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f1 = dd_two_sum(f1,p,&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f0 = dd_two_prod(a[0],b[0],&e);
   f1 = dd_two_sum(f1,e,&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;

   pd_fast_renorm(f0,f1,f2,f3,f4,f5,&c[0],&c[1],&c[2],&c[3],&c[4]);
}

void pd_mul_pd_d ( const double *a, double b, double *c )
{
   // ALGORITHM : baileyMul_fast<5,1,5>

   double f0,f1,f2,f3,f4,f5,e;

   f5 = 0.0;
   f4 = dd_two_prod(a[4],b,&e);
   f5 = f5 + e;
   f3 = dd_two_prod(a[3],b,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f2 = dd_two_prod(a[2],b,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f1 = dd_two_prod(a[1],b,&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;
   f0 = dd_two_prod(a[0],b,&e);
   f1 = dd_two_sum(f1,e,&e);
   f2 = dd_two_sum(f2,e,&e);
   f3 = dd_two_sum(f3,e,&e);
   f4 = dd_two_sum(f4,e,&e);
   f5 = f5 + e;

   pd_fast_renorm(f0,f1,f2,f3,f4,f5,&c[0],&c[1],&c[2],&c[3],&c[4]);
}

void pd_div ( const double *a, const double *b, double *c )
{
   double acc[5];
   double q0,q1,q2,q3,q4,q5;

   q0 = a[0]/b[0]; pd_mul_pd_d(b,q0,acc); pd_sub(a,acc,c);
   q1 = c[0]/b[0]; pd_mul_pd_d(b,q1,acc); pd_sub(c,acc,c);
   q2 = c[0]/b[0]; pd_mul_pd_d(b,q2,acc); pd_sub(c,acc,c);
   q3 = c[0]/b[0]; pd_mul_pd_d(b,q3,acc); pd_sub(c,acc,c);
   q4 = c[0]/b[0]; pd_mul_pd_d(b,q4,acc); pd_sub(c,acc,c);
   q5 = c[0]/b[0];

   pd_fast_renorm(q0,q1,q2,q3,q4,q5,&c[0],&c[1],&c[2],&c[3],&c[4]);
}

/******************** random number generator **************************/

void pd_random ( double *x )
{
   const double eps = 2.220446049250313e-16; // 2^(-52)
   const double eps2 = eps*eps;
   const double eps3 = eps*eps2;
   const double eps4 = eps*eps3;
   const double r0 = ((double) rand())/RAND_MAX;
   const double r1 = ((double) rand())/RAND_MAX;
   const double r2 = ((double) rand())/RAND_MAX;
   const double r3 = ((double) rand())/RAND_MAX;
   const double r4 = ((double) rand())/RAND_MAX;

   x[0] = r0; x[1] = 0.0; x[2] = 0.0; x[3] = 0.0; x[4] = 0.0;
   pd_add_pd_d(x,r1*eps,x);
   pd_add_pd_d(x,r2*eps2,x);
   pd_add_pd_d(x,r3*eps3,x);
   pd_add_pd_d(x,r4*eps4,x);
}

/************************ basic output *********************************/

void pd_write_doubles ( const double* x )
{
   printf("  thumb = %21.14e",x[0]);
   printf("  index = %21.14e\n",x[1]);
   printf("  middle = %21.14e\n",x[2]);
   printf("  ring = %21.14e",x[3]);
   printf("   pink = %21.14e\n",x[4]);
}
