with Standard_Floating_Numbers;          use Standard_Floating_Numbers;

package Triple_Double_Numbers is

-- DESCRIPTION :
--   This package defines triple double numbers and the arithmetic
--   to triple the precision of the (standard hardware) doubles.

-- ACKNOWLEDGEMENTS :
--   The code is based on QD-2.3.9 (Y. Hida, X.S. Li, and D.H. Bailey),
--   as triple doubles are the middle between double double
--   and quad double arithmetic.  The arithmetical functions are
--   translations of the code generated by the CAMPARY library.
--   CAMPARY is the CudA Multiple Precision ARithmetic librarY,
--   by Mioara Joldes, Olivier Marty, Jean-Michel Muller,
--   Valentina Popescu and Warwick Tucker. 

  type triple_double is private;

-- CONSTRUCTORS :

  function create ( x : double_float ) return triple_double;

  -- DESCRIPTION :
  --   The highest word in the triple double on return is x.

  function create ( hi,mi,lo : double_float ) return triple_double;

  -- DESCRIPTION :
  --   Returns a triple double with highest part equal to hi,
  --   middle part equal to mi, and lowest part equal to lo.

-- SELECTORS :

  function hi_part ( x : triple_double ) return double_float;

  -- DESCRIPTION :
  --   Returns the highest word, the most significant part of x.

  function mi_part ( x : triple_double ) return double_float;

  -- DESCRIPTION :
  --   Returns the middle word, the second most significant part of x.

  function lo_part ( x : triple_double ) return double_float;

  -- DESCRIPTION :
  --   Returns the lowest word, the least significant part of x.

-- ARITHMETICAL OPERATIONS :

  function "+" ( x,y : triple_double ) return triple_double; -- returns x+y

  function "-" ( x : triple_double ) return triple_double; -- returns -x

  function "-" ( x,y : triple_double ) return triple_double; -- returns x-y

  function "*" ( x,y : triple_double ) return triple_double; -- returns x*y
  function "*" ( x : triple_double; y : double_float ) return triple_double;
  function "*" ( x : double_float; y : triple_double ) return triple_double;

  function "/" ( x,y : triple_double ) return triple_double; -- returns x/y

private

  type triple_double is record
    hi : double_float; -- highest word, most significant part
    mi : double_float; -- middle word, second most significant part
    lo : double_float; -- lowest word, least significant part
  end record;

end Triple_Double_Numbers;
