# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

# MAKEFILE = makefile_windows2
# MAKEFILE = makefile_windows
MAKEFILE = makefile_unix

test_convolution_jobs:
	make -f $(MAKEFILE) test_convolution_jobs

test_complexconv_jobs:
	make -f $(MAKEFILE) test_complexconv_jobs

test_addition_jobs:
	make -f $(MAKEFILE) test_addition_jobs

test_complexadd_jobs:
	make -f $(MAKEFILE) test_complexadd_jobs

test_dbl_polynomials:
	make -f $(MAKEFILE) test_dbl_polynomials

test_dbl2_polynomials:
	make -f $(MAKEFILE) test_dbl2_polynomials

test_dbl3_polynomials:
	make -f $(MAKEFILE) test_dbl3_polynomials

test_dbl4_polynomials:
	make -f $(MAKEFILE) test_dbl4_polynomials

test_dbl5_polynomials:
	make -f $(MAKEFILE) test_dbl5_polynomials

test_dbl8_polynomials:
	make -f $(MAKEFILE) test_dbl8_polynomials

test_dbl10_polynomials:
	make -f $(MAKEFILE) test_dbl10_polynomials

test_polynomials:
	make -f $(MAKEFILE) test_polynomials

run_dbl_polynomials:
	make -f $(MAKEFILE) run_dbl_polynomials

run_dbl2_polynomials:
	make -f $(MAKEFILE) run_dbl2_polynomials

run_dbl3_polynomials:
	make -f $(MAKEFILE) run_dbl3_polynomials

run_dbl4_polynomials:
	make -f $(MAKEFILE) run_dbl4_polynomials

run_dbl5_polynomials:
	make -f $(MAKEFILE) run_dbl5_polynomials

run_dbl8_polynomials:
	make -f $(MAKEFILE) run_dbl8_polynomials

run_dbl10_polynomials:
	make -f $(MAKEFILE) run_dbl10_polynomials

run_polynomials:
	make -f $(MAKEFILE) run_polynomials

test_dbl_cycsys:
	make -f $(MAKEFILE) test_dbl_cycsys

test_dbl2_cycsys:
	make -f $(MAKEFILE) test_dbl2_cycsys

test_dbl4_cycsys:
	make -f $(MAKEFILE) test_dbl4_cycsys

test_dbl8_cycsys:
	make -f $(MAKEFILE) test_dbl8_cycsys

clean:
	make -f $(MAKEFILE) clean

cleanall:
	make -f $(MAKEFILE) cleanall
