# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

# MAKEFILE = makefile_windows2
# MAKEFILE = makefile_windows
MAKEFILE = makefile_unix

test_dbl_vectors:
	make -f $(MAKEFILE) test_dbl_vectors

test_dbl_matrices:
	make -f $(MAKEFILE) test_dbl_matrices

test_upper_jobs:
	make -f $(MAKEFILE) test_upper_jobs

test_dbl_linearization:
	make -f $(MAKEFILE) test_dbl_linearization

test_dbl_factors:
	make -f $(MAKEFILE) test_dbl_factors

test_dbl2_factors:
	make -f $(MAKEFILE) test_dbl2_factors

test_dbl4_factors:
	make -f $(MAKEFILE) test_dbl4_factors

test_dbl8_factors:
	make -f $(MAKEFILE) test_dbl8_factors

test_dbl_tabs:
	make -f $(MAKEFILE) test_dbl_tabs

test_dbl2_tabs:
	make -f $(MAKEFILE) test_dbl2_tabs

test_dbl4_tabs:
	make -f $(MAKEFILE) test_dbl4_tabs

test_dbl8_tabs:
	make -f $(MAKEFILE) test_dbl8_tabs

make_data_files:
	make -f $(MAKEFILE) make_data_files

test_dbl_baqr:
	make -f $(MAKEFILE) test_dbl_baqr

test_dbl2_baqr:
	make -f $(MAKEFILE) test_dbl2_baqr

test_dbl4_baqr:
	make -f $(MAKEFILE) test_dbl4_baqr

test_dbl8_baqr:
	make -f $(MAKEFILE) test_dbl8_baqr

test_dbl_qrbs:
	make -f $(MAKEFILE) test_dbl_qrbs

test_dbl2_qrbs:
	make -f $(MAKEFILE) test_dbl2_qrbs

test_dbl4_qrbs:
	make -f $(MAKEFILE) test_dbl4_qrbs

test_dbl8_qrbs:
	make -f $(MAKEFILE) test_dbl8_qrbs

clean:
	make -f $(MAKEFILE) clean

cleanall:
	make -f $(MAKEFILE) cleanall
