# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

# MAKEFILE = makefile_windows
MAKEFILE = makefile_unix

test_double_doubles:
	make -f $(MAKEFILE) test_double_doubles

test_triple_doubles:
	make -f $(MAKEFILE) test_triple_doubles

test_penta_doubles:
	make -f $(MAKEFILE) test_penta_doubles

run_dbl_norm:
	make -f $(MAKEFILE) run_dbl_norm

run_dbl2_norm:
	make -f $(MAKEFILE) run_dbl2_norm

test_dbl_norm:
	make -f $(MAKEFILE) test_dbl_norm

test_dbl2_norm:
	make -f $(MAKEFILE) test_dbl2_norm

run_cmplx_norm:
	make -f $(MAKEFILE) run_cmplx_norm

test_cmplx_norm:
	make -f $(MAKEFILE) test_cmplx_norm

test_cmplx2_norm:
	make -f $(MAKEFILE) test_cmplx2_norm

clean:
	make -f $(MAKEFILE) clean
