# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

# MAKEFILE = makefile_windows
MAKEFILE = makefile_unix

run_norm_d:
	make -f $(MAKEFILE) run_norm_d

test_norm_d:
	make -f $(MAKEFILE) test_norm_d

clean:
	make -f $(MAKEFILE) clean
