# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

MAKEFILE = makefile_windows2
# MAKEFILE = makefile_windows2
# MAKEFILE = makefile_unix

test_double_doubles:
	make -f $(MAKEFILE) test_double_doubles

test_triple_doubles:
	make -f $(MAKEFILE) test_triple_doubles

test_quad_doubles:
	make -f $(MAKEFILE) test_quad_doubles

test_penta_doubles:
	make -f $(MAKEFILE) test_penta_doubles

test_octo_doubles:
	make -f $(MAKEFILE) test_octo_doubles

test_deca_doubles:
	make -f $(MAKEFILE) test_deca_doubles

test_hexa_doubles:
	make -f $(MAKEFILE) test_hexa_doubles

run_dbl_norm:
	make -f $(MAKEFILE) run_dbl_norm

run_dbl2_norm:
	make -f $(MAKEFILE) run_dbl2_norm

run_dbl3_norm:
	make -f $(MAKEFILE) run_dbl3_norm

run_dbl4_norm:
	make -f $(MAKEFILE) run_dbl4_norm

run_dbl5_norm:
	make -f $(MAKEFILE) run_dbl5_norm

run_dbl8_norm:
	make -f $(MAKEFILE) run_dbl8_norm

run_dbl10_norm:
	make -f $(MAKEFILE) run_dbl10_norm

test_dbl_norm:
	make -f $(MAKEFILE) test_dbl_norm

test_dbl2_norm:
	make -f $(MAKEFILE) test_dbl2_norm

test_dbl3_norm:
	make -f $(MAKEFILE) test_dbl3_norm

test_dbl4_norm:
	make -f $(MAKEFILE) test_dbl4_norm

test_dbl5_norm:
	make -f $(MAKEFILE) test_dbl5_norm

test_dbl8_norm:
	make -f $(MAKEFILE) test_dbl8_norm

test_dbl10_norm:
	make -f $(MAKEFILE) test_dbl10_norm

run_cmplx_norm:
	make -f $(MAKEFILE) run_cmplx_norm

run_cmplx2_norm:
	make -f $(MAKEFILE) run_cmplx2_norm

run_cmplx3_norm:
	make -f $(MAKEFILE) run_cmplx3_norm

run_cmplx4_norm:
	make -f $(MAKEFILE) run_cmplx4_norm

run_cmplx5_norm:
	make -f $(MAKEFILE) run_cmplx5_norm

run_cmplx8_norm:
	make -f $(MAKEFILE) run_cmplx8_norm

run_cmplx10_norm:
	make -f $(MAKEFILE) run_cmplx10_norm

test_cmplx_norm:
	make -f $(MAKEFILE) test_cmplx_norm

test_cmplx2_norm:
	make -f $(MAKEFILE) test_cmplx2_norm

test_cmplx3_norm:
	make -f $(MAKEFILE) test_cmplx3_norm

test_cmplx4_norm:
	make -f $(MAKEFILE) test_cmplx4_norm

test_cmplx5_norm:
	make -f $(MAKEFILE) test_cmplx5_norm

test_cmplx8_norm:
	make -f $(MAKEFILE) test_cmplx8_norm

test_cmplx10_norm:
	make -f $(MAKEFILE) test_cmplx10_norm

clean:
	make -f $(MAKEFILE) clean
