# Code has been tested on Linux on Windows.
# Set the definition of MAKEFILE below to
# correspond to the proper operating system.

MAKEFILE = makefile_linux
# MAKEFILE = makefile_windows

smTCGemm:
	make -f $(MAKEFILE) smTCGemm

pi64bits:
	make -f $(MAKEFILE) pi64bits

test_split:
	make -f $(MAKEFILE) test_split

test_vdd:
	make -f $(MAKEFILE) test_vdd

clean:
	make -f $(MAKEFILE) clean
