# Code has been tested on Linux on Windows.
# Set the definition of MAKEFILE below to
# correspond to the proper operating system.

MAKEFILE = makefile_linux
# MAKEFILE = makefile_windows

smTCGemm:
	make -f $(MAKEFILE) smTCGemm

clean:
	make -f $(MAKEFILE) clean
