# Code has been tested on Linux on Windows.
# Set the definition of MAKEFILE below to
# correspond to the proper operating system.

MAKEFILE = makefile_linux
# MAKEFILE = makefile_windows

smTCGemm:
	make -f $(MAKEFILE) smTCGemm

test_smDMMA:
	make -f $(MAKEFILE) test_smDMMA

pi64bits:
	make -f $(MAKEFILE) pi64bits

test_split:
	make -f $(MAKEFILE) test_split

test_mmm:
	make -f $(MAKEFILE) test_mmm

test_vdd:
	make -f $(MAKEFILE) test_vdd

test_vqd:
	make -f $(MAKEFILE) test_vqd

test_vod:
	make -f $(MAKEFILE) test_vod

test_vhd:
	make -f $(MAKEFILE) test_vhd

clean:
	make -f $(MAKEFILE) clean
