# The code has been tested on Linux and Windows.
# Swap the # symbol in the definition of the MAKEFILE below
# to use the makefile_windows or the makefile_unix,
# respectively for a Windows or GNU Linux/Unix computer.

# MAKEFILE = makefile_windows2
# MAKEFILE = makefile_windows
MAKEFILE = makefile_unix

test_convolutions:
	make -f $(MAKEFILE) test_convolutions

test_monomials:
	make -f $(MAKEFILE) test_monomials

test_dbl_convolutions:
	make -f $(MAKEFILE) test_dbl_convolutions

test_dbl2_convolutions:
	make -f $(MAKEFILE) test_dbl2_convolutions

test_dbl3_convolutions:
	make -f $(MAKEFILE) test_dbl3_convolutions

test_dbl4_convolutions:
	make -f $(MAKEFILE) test_dbl4_convolutions

test_dbl5_convolutions:
	make -f $(MAKEFILE) test_dbl5_convolutions

test_dbl8_convolutions:
	make -f $(MAKEFILE) test_dbl8_convolutions

test_dbl10_convolutions:
	make -f $(MAKEFILE) test_dbl10_convolutions

test_dbl_monomials:
	make -f $(MAKEFILE) test_dbl_monomials

test_dbl2_monomials:
	make -f $(MAKEFILE) test_dbl2_monomials

test_dbl3_monomials:
	make -f $(MAKEFILE) test_dbl3_monomials

test_dbl4_monomials:
	make -f $(MAKEFILE) test_dbl4_monomials

test_dbl5_monomials:
	make -f $(MAKEFILE) test_dbl5_monomials

test_dbl8_monomials:
	make -f $(MAKEFILE) test_dbl8_monomials

test_dbl10_monomials:
	make -f $(MAKEFILE) test_dbl10_monomials

clean:
	make -f $(MAKEFILE) clean
