with Standard_Integer_Numbers;           use Standard_Integer_Numbers;
with Standard_Floating_Numbers;          use Standard_Floating_Numbers;
with Standard_Floating_Vectors;

package Balanced_Quarter_Doubles is

-- DESCRIPTION :
--   A double is quarter balanced is its quarters are sign balanced
--   (that is: all doubles have the same sign as the leading quarter)
--   and the exponents of the quarters are 0, -4, -8, -12.

  function Thirteen_Random_Bits return integer64;

  -- DESCRIPTION :
  --   Returns a thirteen bit number, of the format 1 bbbb bbbb bbbb,
  --   starting at 1 and 0 or 1 for every 'b' in the format.

  function Random_Quarter ( e : in integer32 ) return double_float;

  -- DESCRIPTION :
  --   Returns a random double where the fraction is generated by
  --   Thirteen_Random_Bits and with exponent e.

  procedure Random ( x0,x1,x2,x3 : out double_float );

  -- DESCRIPTION :
  --   Makes a random balanced quarter double.

  procedure Random ( dim : in integer32;
                     x0,x1,x2,x3 : out Standard_Floating_Vectors.Vector );

  -- DESCRIPTION :
  --   Makes vectors of random balanced quarter doubles.

  -- REQUIRED : x0'range, x1'range, x2'range, x3'range includes 1..dim.

end Balanced_Quarter_Doubles;
